# Generated by Django 3.2.9 on 2022-03-10 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIDDING',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BIDS', models.IntegerField(null=True)),
                ('NAME', models.CharField(max_length=20)),
                ('ITEM', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CATEGORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CARTEGORYNAME', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMMENT', models.CharField(max_length=50)),
                ('USER', models.CharField(max_length=20, null=True)),
                ('ITEM', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=20)),
                ('DESCRIPTION', models.CharField(max_length=60)),
                ('CATEGORY', models.CharField(max_length=50)),
                ('BID', models.IntegerField()),
                ('IMAGE', models.ImageField(blank=True, null=True, upload_to='images')),
                ('TIME', models.CharField(max_length=20)),
                ('OWNER', models.CharField(max_length=20, null=True)),
                ('BIDGATE', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mywatchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionitem', models.ManyToManyField(blank=True, null=True, related_name='auctionitem_userwatchlist', to='auctions.Create')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userwatchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
